name: Automated Stockpile Update

on:    
  schedule:
    - cron: '0 5 * * 0' # Runs every Sunday at 5 AM UTC  
  push:
    paths:
      - '.github/workflows/automated_stockpile_updates.yml' # Runs when this file is modified
  workflow_dispatch: # Allows manual triggering

jobs:
  update-stockpile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install numpy requests matplotlib prettytable

      - name: Run Stockpile Updates
        run: |
          script_dir=$(pwd)
          stockpile_in_dir=${script_dir}/templates/stockpile
          stockpile_out_dir=${script_dir}/campaign/notes/stockpile

          echo "Script dir: ${script_dir}"
          echo "Stockpile input dir: ${stockpile_in_dir}"
          echo "Stockpile output dir: ${stockpile_out_dir}"

          echo "Updating git repo and files to latest!"
          cd ${script_dir}/templates/stockpile
          git checkout automated-updates
          git pull
          sleep 1

          echo "Running the stockpile update!"
          ./stockpile.py -g ${stockpile_in_dir}/stockpile_master_general.txt -t ${stockpile_in_dir}/stockpile_master_trade.txt -o ${stockpile_in_dir}/stockpile_inventory_lists.input -b ${stockpile_in_dir}/stockpile_buy_history.txt -s ${stockpile_in_dir}/stockpile_sell_history.txt
          sleep 1

          echo "Running the stockpile plot generation!"
          ./stockpile_plot.py -b ${stockpile_in_dir}/stockpile_buy_history.txt -s ${stockpile_in_dir}/stockpile_sell_history.txt -o ${stockpile_out_dir}/plots
          sleep 1

          echo "Updating the stockpile HTML pages!"
          cd ${script_dir}/templates
          ./creator.py -f ${stockpile_in_dir}/stockpile_inventory_lists.input
          sleep 1

          echo "Updating the git repo with the new files!"
          git add -A
          git commit -m "Automatic stockpile update."
          git push origin automated-updates
          sleep 1

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Antonius Torode'
          git config --global user.email 'torodean@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git add -A
          git commit -m "Automatic stockpile update."
          git push origin automated-updates
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
