name: Running Automated Tests

on:
  push:
    branches:
      - tests
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install bs4
        pip install tkinter
        pip install cssbeautifier
        # Install pytest
        pip install pytest

    - name: Run tests
      run: |
        cd templates/tests
        pytest -vv test_mmorpdnd.py test_creator.py test_purge_index_files.py test_reset_all_files.py
